-- Zapnutie Row Level Security (default-deny) na všetkých app tabuľkách.
-- SECURITY_AUDIT_2026-06-29.md — M-3b. Defense-in-depth: Prisma sa pripája rolou
-- `postgres` (vlastník + BYPASSRLS) → app funguje bez zmeny; `anon`/`authenticated`
-- (BYPASSRLS=false, bez DML grantov, public schéma nevystavená cez Data API) sú odteraz
-- aj na DB úrovni default-deny. ŽIADNE policies = nikto okrem bypass rolí nečíta/nepíše.
-- ENABLE na už zapnutej tabuľke je no-op (idempotentné). Bez FORCE — vlastník zámerne obchádza.

ALTER TABLE "AccessRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Cart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CartItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CompanyDispenser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeliveryLocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DispenserModel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DispenserRefill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DocDedup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderCounter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderStatusEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PohodaSyncJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PriceTier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductGroup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductMedia" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductPrice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductSource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RateLimit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncCursor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
